### ISSUE TITLE
关于RaSa电商聊天客服机器人的开发过

### ISSUE THREAD

**Issue by ume-technology** [ume-technology/ume-technology#3]

**Comment by ume-technology** [comment]
- [ ] 关于config.yml中RegexEntityExtractor组件没有被配置的警告，config的配置如下：
```
pipeline:
  - name: SpacyNLP
    model: zh_core_web_lg
    case_sensitive: False  # 表示 hello 和 Hello 相同意思
  - name: SpacyTokenizer
    token_pattern: None
  - name: SpacyFeaturizer
    pooling: mean
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: SpacyEntityExtractor
    dimensions: ["goods"]
  - name: RegexFeaturizer
    case_sensitive: False
    use_word_boundaries: False # 配置了 lookup table 时使用
  - name: RegexEntityExtractor
    case_sensitive: False # 大小写不敏感
    use_lookup_tables: False
    use_regexes: True
    use_word_boundaries: False # 配置了 lookup table 时使用
```
